ditrit/OGrEE-Core

API/models/schemas/device_schema.json, CLI/controllers/commandController.go, CLI/lexer.go, CLI/parser.go, CLI/parser_test.go
This PR depends on PR #30, which should be merged first.
=> type check for temperatures is done by the schema rather than the CLI

API/models/base.go
This provides a fix for the case when the API does not have credentials. The API would show that it was connected and provide incorrect log messages. 
Now the API will only proceed after having fully established authorisation. This is done by performing a DB Name search (which is only allowed for authorised users) for the target DB_NAME
=> dbAuthCheck

APP/ogree_app/lib/common/api_backend.dart, APP/ogree_app/lib/pages/results_page.dart, APP/ogree_app/lib/pages/select_page.dart, APP/ogree_app/lib/widgets/select_date.dart, APP/ogree_app/lib/widgets/select_namespace.dart, APP/ogree_app/lib/widgets/select_objects/app_controller.dart, APP/ogree_app/lib/widgets/select_objects/select_objects.dart, APP/ogree_app/test/results_page_test.dart, APP/ogree_app/test/select_date_test.dart, APP/ogree_app/test/select_objects_test.dart, APP/ogree_app/test/select_page_test.dart
Better date and namespace choices, correct filtering and correct message with no objects found.
=> Date filtering fix

APP/ogree_app/lib/common/theme.dart, APP/ogree_app/lib/models/user.dart, APP/ogree_app/lib/pages/tenant_page.dart, APP/ogree_app/lib/widgets/select_objects/tree_view/tree_node_tile.dart, APP/ogree_app/lib/widgets/tenants/popups/user_popup.dart, APP/ogree_app/lib/widgets/tenants/user_view.dart
And also, link from domain view to users view.
=> Add search and sort to Users View

.github/actions/build/CLI/action.yaml, .github/actions/build/docker/action.yaml, .github/actions/build/flutter-app/action.yaml, .github/actions/build/multi-docker/action.yaml, .github/actions/utils/wait-job/action.yaml, .github/workflows/build-docker-deploy.yaml, .github/workflows/versioning-release-candidate.yaml, .github/workflows/versioning-release.yaml
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Please describe the tests that you ran to verify your changes. 
Provide instructions so we can reproduce. 
Please also list any relevant details for your test configuration
=> chore(ci): Build ans push docker image to registery

.github/workflows/build-docker-deploy.yaml, .github/workflows/versioning-release-candidate.yaml, .github/workflows/versioning-release.yaml
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Please describe the tests that you ran to verify your changes. 
Provide instructions so we can reproduce. 
Please also list any relevant details for your test configuration
=> chore(ci): correct trigger for release build

APP/ogree_app/lib/common/api_backend.dart, APP/ogree_app_backend/api.go
=> fix(app): correct backend response when unable to get docker info

.github/actions/build/back-app/linux/action.yaml, .github/actions/build/back-app/windows/action.yaml, .github/actions/build/multi-docker/action.yaml, .github/workflows/build-docker-deploy.yaml
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Please describe the tests that you ran to verify your changes. 
Provide instructions so we can reproduce. 
Please also list any relevant details for your test configuration
=> fix(ci): build backend-app with ci

APP/ogree_app/lib/common/api_backend.dart, APP/ogree_app/lib/common/appbar.dart, APP/ogree_app/lib/l10n/app_en.arb, APP/ogree_app/lib/l10n/app_fr.arb, APP/ogree_app/lib/pages/login_page.dart, APP/ogree_app/lib/widgets/tenants/locked_view.dart, APP/ogree_app/lib/widgets/tenants/popups/create_server_popup.dart, APP/ogree_app/lib/widgets/tenants/popups/create_tenant_popup.dart, APP/ogree_app/lib/widgets/tenants/popups/update_tenant_popup.dart, APP/ogree_app/lib/widgets/tenants/tenant_card.dart, APP/ogree_app/test/login_page_test.dart, APP/ogree_app_backend/api.go
Adapt backend login/version response and the frontend to identify docker or kubernetes back, adapting UI accordingly. 
Fixes #173 
- Local test with webapp version
=> [SuperAdmin] Add support to Kubernetes backend

CLI/main.go
=> feat(cli): print API URL on startup

inno-wininstaller.iss
When uninstalling, it will now remove logs and cache created by the apps after install.
- Local test on Windows
=> fix(ci) add remove files to windows installer

API/controllers/entityController.go, API/main.go, API/main_test.go, API/models/model.go, API/swagger.json, API/utils/util.go, APP/ogree_app/lib/common/api_backend.dart, APP/ogree_app/lib/pages/select_page.dart, APP/ogree_app/lib/pages/tenant_page.dart, APP/ogree_app/lib/widgets/select_namespace.dart, APP/ogree_app/lib/widgets/select_objects/app_controller.dart, APP/ogree_app/lib/widgets/select_objects/select_objects.dart, APP/ogree_app/lib/widgets/select_objects/tree_view/tree_node_tile.dart, APP/ogree_app/lib/widgets/tenants/popups/user_popup.dart, APP/ogree_app/test/select_objects_test.dart
Hierarchy endpoint now accepts namespaces, limit (depth), startDate and endDate as query params.
Fixes #197 
- Local test with local API and Flutter webapp.
=> Extend hierarchy endpoint with namespaces

API/controllers/entityController.go
=> fix(api): delete wildcard sends wrong status

CLI/controllers/tree.go
Only the name of the groups was printed in /Logical/Groups (not the full id), and the corresponding get was therefore not working.
=> fix(cli): show full id in /Logical/Groups

.github/workflows/api-unit-test.yml, API/controllers/entityController.go, API/models/model.go, API/utils/util.go
Add ?limit=X to /api/entites for depth when entities=domains|devices|stray, ignored for the rest.
Fixes #212
- Local test using Postman
=> feat(api) add limit to entities endpoint

APP/lib/common/api_backend.dart, APP/lib/widgets/tenants/popups/create_tenant_popup.dart, BACK/docker-backend/tenant.go, deploy/docker/docker-compose.yml
Implements stream with docker command output from back to front (flutter app).
Fixes #214
- Local test using Windows app + docker back
=> [SuperAdmin] Give user feedback on docker create tenant command

CLI/ast.go, CLI/controllers/commandController.go, CLI/controllers/commandController_test.go, CLI/controllers/controllerUtils.go, CLI/controllers/initController.go, CLI/main.go, CLI/models/unity.go, CLI/repl.go
Reconnect to OGrEE-3D when executing any command that necessarily requires the connection to be established.
Unit tests + test with the CLI by executing the command draw
=> Feature cli autoreconnect

APP/lib/common/api_backend.dart, APP/lib/widgets/tenants/popups/create_tenant_popup.dart, APP/lib/widgets/tenants/popups/update_tenant_popup.dart, BACK/docker-backend/tenant.go
Fix stream of docker output from backend to webapp. Also adds it to update tenant.
Fixes #231
- Local test using webapp and Windows app
=> [SuperAdmin] Fix docker live output for webapp

inno-wininstaller.iss
Add/remove the backend as an auto windows service during install/uninstall on Windows.
Fixes #236
- Local test on Windows
=> [WindowsInstaller] Create backend as Windows Service

.gitignore, API/Dockerfile.dev, API/ReadMe.md, API/main.go, API/resources/test/.env, deploy/README.md, deploy/docker/.env, deploy/docker/Makefile, deploy/docker/docker-compose.dev.yml, deploy/docker/docker-compose.yml
Add a development deploy to facilitate api development. For details see the information added to readme
- Local test
=> Feature dev deploy

APP/lib/common/api_backend.dart, BACK/docker-backend/auth/middleware.go
The current message if only "401" is not at all clear.
Fixes #250
- Local test with webapp
=> [SuperAdmin] Better reporting to user of auth token expiration

.github/workflows/wiki.yml, wiki/CLI-Environment.md, wiki/CLI-language.md, wiki/Home.md, wiki/JSON-templates-definitions.md, wiki/Linux-dev-enviroment.md, wiki/Offline-Install.md, wiki/Quick-Windows-Deploy.md
Make the wiki content to be inside the same repository so that the documentation can be updated in the same pull request as the code. For this we add a github Action that detects changes in the wiki/ folder and pushes the changes to the wiki repository.
=> docs: wiki inside repo

.github/workflows/wiki.yml
now the wiki update is done by the user who generated the action (usually the author of the commit) and the wiki version name has information about the commit
=> fix user and comment for wiki update

wiki/CLI-language.md
More documentation about the ocli language.
- Documentation
=> docs(cli): ocli language

.github/dependabot.yml
=> Fix(ci) update bot to ignore major

CLI/ast.go, CLI/controllers/commandController.go
```
draw _
undraw _
```
now draws or undraws the current selection.
Fixes #248 
=> feat(cli): draw/undraw selection

.github/actions/build/API/action.yaml, .github/actions/build/CLI/action.yaml, .github/actions/build/flutter-app/linux/action.yaml, .github/actions/build/multi-docker/action.yaml, .github/actions/build/windows/action.yaml, .github/workflows/build-docker-deploy.yaml, APP/lib/common/snackbar.dart, APP/lib/l10n/app_en.arb, APP/lib/l10n/app_fr.arb, APP/lib/models/netbox.dart, APP/lib/pages/projects_page.dart, APP/lib/pages/results_page.dart, APP/lib/widgets/tenants/popups/backup_popup.dart, APP/lib/widgets/tools/download_cli_popup.dart
This adds the creation of a release at GitHub with the binaries and the possibility to download the CLI from the SuperAdmin Flutter app.
Fixes #282 
- Local test with Mac app and web app.
- CI tested in a separate fork.
=> Download CLI with SuperAdmin + Github release

CLI/controllers/commandController.go, CLI/controllers/stateController.go, CLI/controllers/tree.go, CLI/main.go
This adds the domain of the current object to the prompt :
- Manual tests with a local CLI.
=> feat(cli): adds current domain to prompt

.github/workflows/api-unit-test.yml, .github/workflows/cli-unit-test.yml, .github/workflows/flutter-test.yml
Also run tests on push to main branch
-
=> ci(all): run tests on main

CLI/ast.go, CLI/controllers/commandController.go, CLI/controllers/draw.go, CLI/controllers/layers_test.go, CLI/controllers/select.go
Allows to execute draw, undraw and update commands on layers.
Fixes https://github.com/ditrit/OGrEE-Core/issues/102
Automatic tests
Manual test with cli and 3d
=> feat(cli): draw, undraw and update layer

.github/workflows/wiki-conflicts.yml
Verify that the changes made in wiki/ do not conflict with changes made on the wiki in the web page
=> feat(ci): verify conflicts in wiki on pull requests

APP/lib/common/api_backend.dart, deploy/app/launch.sh
Fix app launch and docker status for tenants with upper case chars.
Fixes #333 
Fixes #328 
- Local test
=> Fix APP bugs: launch.sh on Mac and tenant docker status

APP/lib/common/api_backend.dart, APP/lib/l10n/app_en.arb, APP/lib/l10n/app_fr.arb, APP/lib/pages/tenant_page.dart, APP/lib/widgets/tenants/docker_view.dart, APP/lib/widgets/tenants/popups/confirm_popup.dart, APP/lib/widgets/tenants/popups/create_tenant_popup.dart, APP/lib/widgets/tenants/popups/update_tenant_popup.dart, APP/lib/widgets/tenants/tags_view.dart, APP/lib/widgets/tenants/tenant_card.dart, APP/lib/widgets/tenants/user_view.dart, APP/lib/widgets/tools/tool_card.dart, BACK/app/handlers/docker/tenant.go, BACK/app/services/router.go
Now, a delete tenant will also remove the db volume. Stop/start tentant functionality added. 
Fixes #377 
- Local test on MacOS
=> Stop/start tenant + remove db volume 

.github/actions/build/API/action.yaml
- Updated the required Go version for the API build to 1.21
- Fixes #388 
=> fix(Github Actions) Update required Go version

APP/lib/common/api_backend.dart, APP/lib/models/netbox.dart, APP/lib/pages/projects_page.dart, APP/lib/widgets/common/delete_dialog_popup.dart, APP/lib/widgets/tools/create_netbox_popup.dart, APP/lib/widgets/tools/tool_card.dart, BACK/app/handlers/docker/app.go, BACK/app/handlers/docker/nautobot.go, BACK/app/handlers/docker/netbox.go, BACK/app/handlers/docker/opendcim.go, BACK/app/handlers/docker/tenant.go, BACK/app/models/tools.go, BACK/app/services/router.go
Add functionality to create and delete Nautobot docker deploy with super admin version of flutter app.
Fixes #383 
- Local test
=> Add Nautobot to SuperAdmin

API/models/validateEntity.go
Fixes wrongfully letting buildings have children and groups having not direct children.
Fixes #428
- Local test
=> Fix wrongful creation of groups for buildings and with not direct child

deploy/db/Dockerfile, deploy/db/README.md
- Fix Dockerfile to load correctly the init scripts that create the replicaSet
Fixes #453
- Local test
=> Fix mongodb Dockerfile

.github/workflows/api-unit-test.yml, .github/workflows/cli-unit-test.yml, API/controllers/auth_test.go, CLI/controllers/commandController_test.go, README.md
Change API test workflow to upload the coverage badge generated to a dedicated branch
Fixes #461 
- Bug fix 
- Local test
=> fix(api) send api coverage badge to dedicated branch

API/models/model.go, APP/lib/l10n/app_en.arb, APP/lib/l10n/app_es.arb, APP/lib/l10n/app_fr.arb, APP/lib/l10n/app_pt.arb, APP/lib/widgets/object_graph_view.dart, APP/lib/widgets/select_objects/object_popup.dart, APP/lib/widgets/select_objects/view_object_popup.dart, CLI/ast.go, CLI/ast_test.go
=> fix(cli) pillars and separators as map

API/models/attributes.go, API/models/update_object_test.go, API/utils/util.go, CLI/controllers/create_test.go, CLI/controllers/link_test.go, CLI/controllers/template.go, CLI/controllers/template_test.go, CLI/controllers/update.go, CLI/controllers/update_test.go, CLI/controllers/utils.go, CLI/models/attributes.go, CLI/models/attributes_device.go, CLI/models/attributes_device_test.go, CLI/models/attributes_test.go, CLI/parser/ast.go, CLI/parser/ast_test.go, CLI/test/utils.go
On a device update, if sizeU or height is modified, the CLI updates the other attribut.
Fixes #487 
- Local test
=> fix(cli) compute sizeU & height on modification

CLI/controllers/template.go, CLI/controllers/template_test.go, CLI/controllers/utils.go, CLI/models/attributes.go, CLI/models/attributes_device.go, CLI/models/attributes_device_test.go, CLI/models/attributes_room.go
Simplify ApplyTemplate functions.
Fixes #496 
- Refactor
- Local test
=> Refactor(cli) ApplyTemplate

APP/lib/common/api_backend.dart, APP/lib/common/theme.dart, APP/lib/models/netbox.dart, APP/lib/pages/projects_page.dart, APP/lib/widgets/tools/create_nbox_popup.dart, APP/lib/widgets/tools/create_netbox_popup.dart, APP/lib/widgets/tools/create_opendcim_popup.dart, BACK/app/handlers/docker/nautobot.go, BACK/app/handlers/docker/netbox.go, BACK/app/handlers/docker/opendcim.go, BACK/app/handlers/docker/tenant.go, BACK/app/handlers/docker/tools-assets/netbox-docker-template.txt, BACK/app/models/tools.go
- Fixes deploy for opendcim and netbox
- Always user the same opendcim and netbox repo version to avoid further issues
- Add option to choose between v3.7 and v4 for netbox deploy.
Fixes #519 
Fixes #518 
- Local test
=> Nautobot, netbox and opendcim deploy improvements
