CLI/controllers/commandController.go
replaces - with \n in InteractObject
=> CLI : description lines are concatenated whitout "\n"

CLI/controllers/commandController.go, CLI/controllers/controllerUtils.go
Closes issue 165 from previous repo : [https://github.com/ditrit/OGrEE-CLI/issues/165](url)
The JSON received from the API can have the following format :
```
{
"errors": [
"/attributes/usableColor does not match pattern '^[0-9a-fA-F]{6}$'",
"missing properties: 'name'",
"additionalProperties 'banana' not allowed"
],
"message": "JSON body doesn't validate with the expected JSON schema",
"status": false
}
```
The "errors" field is currently ignored, this PR fixes it.
=> API error details

CLI/controllers/stateController.go, CLI/parser.go, CLI/repl.go
The parser error messages were not very readable so this PR simplifies them. It also removes the '$' from the prompt.
before : 
```
test@OGrEE3D:/Physical$> +ro:/P/EDF/NOE/BLOG/ARCH@[15.4,39.1]@0@[4.87,2.93,2.5]@+y+y
+ro:/P/EDF/NOE/BLOG/ARCH@[15.4,39.1]@0@[4.87,2.93,2.5]@|+y+y
parsing command
+ro:/P/EDF/NOE/BLOG/ARCH@[15.4,39.1]@0@[4.87,2.93,2.5]@|+y+y
parsing room parameters : parsing axisOrientation
+ro:/P/EDF/NOE/BLOG/ARCH@[15.4,39.1]@0@[4.87,2.93,2.5]@|+y+y
keyword or expr expected
```
after : 
```
test@OGrEE3D:/Physical> +ro:/P/EDF/NOE/BLOG/ARCH@[15.4,39.1]@0@[4.87,2.93,2.5]@+y+y
^
parsing stack : command -> room parameters -> axisOrientation
error : keyword or expr expected
```
=> simplify parser errors

CLI/config/config.go, CLI/controllers/commandController.go, CLI/controllers/initController.go, CLI/logger/logger.go, CLI/utils/util.go
Currently, if the CLI executable is not run from the CLI directory, it will not use the correct paths for the manual pages, the text logs, config.toml etc... This PR fixes it.
=> Hardcoded and config paths are now relative to the executable file

CLI/controllers/commandController.go
Fixes that bug :
```
herve@exaion:/Physical/MGF/RDC/R3> +dv:/P/MGF/RDC/R3/CLIM4    @[1.65,11-.85] @ 0 @[1.75, 0.85]
panic: interface conversion: interface {} is []float64, not string
goroutine 1 [running]:
cli/controllers.GetOCLIAtrributes({0xc00021c8e0, 0x1a}, 0x4, 0xa?)
/OGrEE/OGrEE-Core/CLI/controllers/commandController.go:1676 +0x3465
main.(*createDeviceNode).execute(0xc00050e5c0)
/OGrEE/OGrEE-Core/CLI/ast.go:1228 +0x27e
main.InterpretLine({0xc000240a00?, 0xc000240080?})
/OGrEE/OGrEE-Core/CLI/repl.go:28 +0x52
main.Start(0xc0002120a8, {0xc0000ac648, 0x5})
/OGrEE/OGrEE-Core/CLI/repl.go:48 +0x85
main.main()
/OGrEE/OGrEE-Core/CLI/main.go:68 +0x79f
```
=> fixes incomplete type switch for posU/slot

CLI/ast.go, CLI/parser.go
A message is now printed when an empty selection is made.
Fixes #116
=> feat(cli): message on empty selection

deploy/docker/entrypoint.sh
Replaces sleep 10 with log check to see hat mongo is up and running before try to initiate the replica set.
Fixes #157 
- Enhancement
- Local test with Docker and mongo images version 6 and 7
=> chore(deploy) Replace sleep by mongo log check

CLI/ast.go, CLI/parser.go
```
admin@alvea:/Physical/CAO/1SS/CVC12> >
panic: runtime error: index out of range [0] with length 0
goroutine 1 [running]:
cli/controllers.(*HierarchyNode).FindNode(0x0?, {0x0?, 0xc12cb0?})
/workdir/controllers/tree.go:71 +0xc5
cli/controllers.Tree({0x0, 0x0}, 0xc000210240?)
/workdir/controllers/tree.go:227 +0x3c
cli/controllers.CD({0x0, 0x0})
/workdir/controllers/commandController.go:663 +0x66
cli/controllers.FocusUI({0x0, 0x0})
/workdir/controllers/commandController.go:1432 +0x547
main.(*focusNode).execute(0xc0002d421c?)
/workdir/ast.go:153 +0x3a
main.InterpretLine({0xc0002d421c?, 0xc00025a1e0?})
/workdir/repl.go:29 +0x42
main.Start(0xc000214150, {0xc00000ad9a, 0x5})
/workdir/repl.go:54 +0x7a
main.main()
/workdir/main.go:82 +0x83f
```
- [ x ] Bug fix (non-breaking change which fixes …
=> fix(cli): focus command crashing on empty path

CLI/controllers/tree.go
```
>tree / 5
Error : location not found
```
when using tree with imbricated domains, because the /api/domains route was assumed to return only the root domains, which is not the case.
=> fix(cli): tree error with imbricated domains

CLI/parser.go
Even when the parsing stack was empty, sometimes "parsing stack : \n" was printed in the error message.
=> fix(cli): dont print empty parsing stack on error

CLI/parser.go
Fix parsing bug that allows the arguments to be stuck to the command without spaces :
```
getsitename/buildingname
```
- Unit tests
=> fix(cli): enforce spacing before command arguments

CLI/controllers/tree.go
A previous fix (PR #210) caused that bug that prevents groups from showing in /Logical/Groups
=> fix(cli): empty /Logical/Groups

CLI/parser.go
When calling an alias, sometimes the first characters were ignored, causing the call to fail because of undefined function.
- Parser unit tests
=> fix(cli): alias call parsing bug

CLI/ast.go
CLI prints "Separator toto replaced" when a separator is replaced rather than added.
Fixes #206 
=> feat(cli): print separator replaced

APP/Dockerfile, APP/README.md, deploy/README.md, deploy/app/launch.ps1, deploy/app/launch.sh
If a container with the same name already exists an incrementable suffix -X will be added as needed (ogree-superadmin-1, for example). A -f option was added to stop previous containers, releasing the allocated port.
Fixes #253
- Local test with bash and powershell
=> [SuperAdmin] Launch scripts: handle container already exists

CLI/controllers/commandController.go, CLI/other/man/print.md, CLI/other/man/printf.md, CLI/parser.go, CLI/parser_test.go
Removes the parenthesis from the printf, they were causing a bug because of the inconsistency with other commands.
```
printf "41 + 1 equals %03d", 42
```
Also adds the printf man page, and improves print one.
- Documentation
- Unit tests
=> fix(cli): printf syntax + man page

CLI/ast.go
fix bug present since the merge of filtering ls, from which when you get an object that does not exist (get asd for example) it does not show an error message. The error message is only added when the requested path does not have a wildcard, since in that case I do not consider the empty response to be an error.
- Local test on cli
=> fix(cli): show error on get not existent object

API/models/model.go, API/repository/entity.go
Changes to the name of the domain imply changing its id which is used as reference by other objects so now it propagated to them as well. 
Fixes #287
- Local test using Postman
=> Propagate domain ID changes to objects

API/models/schemas/obj_template_schema.json, API/models/schemas/test_data/KO/obj_template4.json, API/models/schemas/test_data/OK/obj_template1.json, API/models/schemas/test_data/OK/obj_template3.json, API/models/validateEntity_test.go
Unify elemOrient for racks and devices, making it required with only two values accepted.
Fixes #316
- Local test using Postman
=> Unify elemOrient on object template schema

CLI/controllers/delete.go, CLI/controllers/tree.go
- Updated `/Logical/Layers` caching logic, preventing `ls` from showing deleted layers;
- Updated `FillUrlTree` and `FillWithMap` logic to reset original node's children list before refilling it, preventing `ls` from showing deleted objects.
Fixes #315 
- Local test creating and deleting objects and calling `ls` to see if they are still listed or not.
=> fix(cli) deleted object not removed

CLI/astflow.go, wiki/CLI-language.md
- Fixes #330 - Added a simple check to verify wether the loop body is empty or not before executing it, avoiding the segfault;
- Fixes #329 - Corrected the integer division operator on the wiki.
- Local test
=> fix(cli) empty for loop causes segfault

API/controllers/entityController.go, API/router/router.go, API/swagger.json, API/utils/util.go, CLI/ast.go, CLI/controllers/create.go, CLI/controllers/delete.go, CLI/controllers/initController.go, CLI/controllers/layer.go, CLI/controllers/layers_test.go, CLI/controllers/update.go, CLI/models/entity.go, CLI/models/layer.go, CLI/parser.go, wiki/CLI-language.md
Adds new functionalities to CLI and API regarding layers:
[API] Adds endpoint to get objects from a layer given a root ID object. 
[CLI] Adds warning message when layer has no filter. 
[CLI] Adds filter to create layer command
[CLI]Apply double wildcard to root as well.
Fixes #324
- Local test
=> Layer improvements

API/models/create_object_test.go, API/models/validateEntity.go
- Edit error messages on function `validateParent` to inform what should be the parent category of an object being created in an incorrect place.
- Removes `device` from list of possible parents of a `u.GROUP`.
Fixes #303 .
- Local test.
=> feat(API) Better error messages on invalid ParentID

CLI/utils/util.go, wiki/CLI-language.md
- Removed logic to append zeroes to the left of a tag color;
- Removed unnecessary line on `CLI Language` Wiki page.
- Fixes #353 
- Local test
=> fix(CLI) Tag creation should not accept a hex value with less than 6 digits

API/models/schemas/bldg_template_schema.json, API/models/schemas/building_schema.json, API/models/schemas/domain_schema.json, API/models/schemas/obj_template_schema.json, API/models/schemas/refs/types.json, API/models/schemas/room_schema.json, API/models/schemas/room_template_schema.json, API/models/schemas/site_schema.json, API/models/schemas/test_data/KO/obj_template4.json, API/models/validateEntity.go, API/models/validateEntity_test.go
- Added a description for each `definition` of type, such as `slug` and `vector2`
- Modified some schemas to reference `types.json`
- Added logic to substitute the regex pattern in validation error messages for the friendlier description
- Updated unit tests for the validation
- Fixes #291 
- Local test
=> feat(API) improved validation error messages

CLI/ast.go, CLI/controllers/interact_test.go
- Added functionality to make `labelBackground` send an **interact** command to the 3D client instead of a **modify** one
- Fixes #357 
- Local test
=> fix(CLI) corrected `labelBackground` command behavior

deploy/app/launch.ps1
Avoid infinite loop due to docker bug that does not let our powershell script get the output of `docker ps`.
Fixes #375
- Local test on Windows with docker desktop v4.27.1.
=> Launch.ps1: avoid loop due to docker bug

API/controllers/entityController.go, CLI/ast.go, CLI/completer.go, CLI/controllers/commandController.go, CLI/other/man/link.txt, CLI/other/man/unlink.txt, CLI/parser.go, wiki/CLI-language.md
Link command now accepts multiple `@attrName=attrValue`, allowing user to set/modify attributes when linking a stray object to a new parent. 
Fixes #382 
- Local test
=> Add attributes to link command

APP/lib/common/api_backend.dart, APP/lib/common/snackbar.dart, APP/lib/l10n/app_en.arb, APP/lib/l10n/app_fr.arb, APP/lib/widgets/common/delete_dialog_popup.dart, APP/lib/widgets/tenants/popups/backup_popup.dart, APP/pubspec.lock, BACK/app/handlers/docker/tenant.go, BACK/app/models/tenants.go, BACK/app/services/router.go
Restore a mongo DB dump to a tenant. As a plus, an error popup for deleting a tenant has longer duration and all the error popups are now "tap to copy".
Fixes #402
- Local test
=> Add DB backup restore to SuperAdmin

CLI/ast.go, CLI/controllers/commandController.go, CLI/controllers/create.go, CLI/controllers/sendSchemaController.go, wiki/CLI-language.md
`+device:dev10@[blade01..blade05]@ibm-example`
The above is now the same as:
`+device:dev10@[blade01,blade02,blade03,blade04,blade05]@ibm-example`
Fixes #413
- Local test
=> Add .. to slots range for devices

API/controllers/image.go, API/controllers/schema.go, API/models/schema.go, API/router/router.go, APP/lib/common/api_backend.dart, APP/lib/widgets/select_objects/object_popup.dart, APP/pubspec.yaml, APP/windows/flutter/CMakeLists.txt
Bundled assets from a relative path were not working correctly for all platforms, so the APP will now request the JSON schemas from the API instead.
Fixes #432
- Local test on Windows and Linux
=> [API] Add get schemas endpoint [APP] Use endpoint insted of assets

CLI/ast.go, CLI/other/man/minus.txt, CLI/other/man/unset.txt, CLI/parser.go
The unset command option to delete object attribute is replaced by a new syntax:
```
-[name]:[attribute]
-siteE:myattr
```
Fixes #436
- Local test
=> Change delete object attribute syntax

API/models/entity_attributes.go, API/models/schemas/device_schema.json, CLI/controllers/create_test.go, CLI/controllers/template_test.go, CLI/controllers/update_test.go, CLI/models/attributes.go, CLI/models/attributes_device.go, CLI/models/attributes_device_test.go, CLI/utils/util.go
In a device, the *sizeU* attribute is now the least integer value greater or equal to the value computed from the height.
Also update json schema to ensure that sizeU is an integer
Fixes #499 
- Local test
=> Fix499 correct sizeu value
